#!/usr/bin/env python3
"""
Debug script with mock LiteLLM to test logic flow without API keys
"""
import asyncio
import sys
import os
sys.path.append('/Users/marcomacri/Desktop/cartella progetti github/pytaskai-public')

# Mock LiteLLM before importing ai_service
class MockResponse:
    def __init__(self, content):
        self.choices = [MockChoice(content)]
        self.usage = MockUsage()

class MockChoice:
    def __init__(self, content):
        self.message = MockMessage(content)

class MockMessage:
    def __init__(self, content):
        self.content = content

class MockUsage:
    def __init__(self):
        self.prompt_tokens = 100
        self.completion_tokens = 200
        self.total_tokens = 300

# Replace litellm with mock
import json
async def mock_acompletion(**kwargs):
    # Return mock task JSON
    mock_task = {
        "title": "Mock Test Task",
        "description": "Generated by mock AI service",
        "details": "Mock implementation details",
        "test_strategy": "Mock testing approach",
        "estimated_hours": 2.0,
        "complexity_score": 5
    }
    return MockResponse(json.dumps(mock_task))

# Monkey patch
import mcp_server.ai_service
mcp_server.ai_service.litellm.acompletion = mock_acompletion

from mcp_server.ai_service import AIService

async def test_ai_service_mock():
    try:
        ai_service = AIService(project_root="/Users/marcomacri/Desktop/cartella progetti github/pytaskai-public")
        
        result = await ai_service.generate_task_with_ai(
            user_prompt="Test task creation with mock",
            use_research=False,
            use_lts_deps=True,
            priority="medium"
        )
        
        print("SUCCESS - Mock test passed!")
        print("Result keys:", list(result.keys()))
        print("Title:", result.get("title", "N/A"))
        return True
        
    except Exception as e:
        print("ERROR:", str(e))
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    try:
        result = asyncio.run(test_ai_service_mock())
        print(f"Mock test result: {result}")
    except Exception as e:
        print(f"Mock test failed: {e}")
        import traceback
        traceback.print_exc()