#!/usr/bin/env python3
"""
Debug script to test MCP tool with mock AI
"""
import asyncio
import sys
import os
import json
sys.path.append('/Users/marcomacri/Desktop/cartella progetti github/pytaskai-public')

# Mock LiteLLM before importing anything
class MockResponse:
    def __init__(self, content):
        self.choices = [MockChoice(content)]
        self.usage = MockUsage()

class MockChoice:
    def __init__(self, content):
        self.message = MockMessage(content)

class MockMessage:
    def __init__(self, content):
        self.content = content

class MockUsage:
    def __init__(self):
        self.prompt_tokens = 100
        self.completion_tokens = 200
        self.total_tokens = 300

async def mock_acompletion(**kwargs):
    # Return mock task JSON
    mock_task = {
        "title": "Mock MCP Test Task",
        "description": "Generated by mock AI service for MCP testing",
        "details": "Mock implementation details with async compatibility",
        "test_strategy": "Mock testing approach for MCP",
        "estimated_hours": 3.0,
        "complexity_score": 6
    }
    return MockResponse(json.dumps(mock_task))

# Monkey patch before importing mcp modules
import mcp_server.ai_service
mcp_server.ai_service.litellm.acompletion = mock_acompletion

import mcp_server.task_manager as tm

async def test_mcp_tool_mock():
    try:
        print("Testing MCP add_task_tool with mock AI...")
        
        # Get the actual function from the MCP tool
        add_task_func = tm.add_task_tool.func  # Access wrapped function
        result = await add_task_func(
            project_root="/Users/marcomacri/Desktop/cartella progetti github/pytaskai-public",
            prompt="Ultimate test: Create a task to confirm all issues (asyncio, path, environment) are resolved and task creation is successful.",
            use_research=False,
            use_lts_deps=True,
            priority="high"
        )
        
        if "error" in result:
            print("ERROR:", result["error"])
            print("Full result:", result)
            return False
        else:
            print("SUCCESS - MCP tool test passed!")
            print("Task ID:", result.get("task_id", "N/A"))
            print("Task title:", result.get("task", {}).get("title", "N/A"))
            return True
        
    except Exception as e:
        print("EXCEPTION:", str(e))
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    try:
        result = asyncio.run(test_mcp_tool_mock())
        print(f"MCP mock test result: {result}")
    except Exception as e:
        print(f"MCP mock test failed: {e}")
        import traceback
        traceback.print_exc()